#define EFOPEN -1
#define EDISK -2
#define EFREAD -3
#define EFWRITE -4
#define EBLOCKID -5
#define EMAGICNUM -6
#define EDISKFULL -7
#define ECONSISTENCY -8
#define EMOUNTERROR -9
#define EBADFD -10
#define ERO -11
#define EEOF -12
#define EBADFILE -13
#define EBADFILENAME -14
#define EFREEBLOCK -15
